# -*- coding: utf-8 -*-
"""
Khung chỉ tiêu chuẩn theo Thông tư 200/2014/TT-BTC.

Mỗi dòng = (ma_so, ten_chi_tieu, cap, loai)
  - ma_so : mã số chỉ tiêu (str) hoặc None nếu là tiêu đề thuần
  - cap   : cấp thụt lề (0,1,2,3) để trình bày trong Excel
  - loai  : 'header' | 'section' | 'item' | 'sub' | 'total'

Bộ parser chỉ cần OCR đúng MÃ SỐ + các con SỐ; nhãn chỉ tiêu lấy từ khung
chuẩn này nên luôn sạch, không bị lỗi OCR.
"""

# ---------------------------------------------------------------------------
# B01-DN : BẢNG CÂN ĐỐI KẾ TOÁN
# ---------------------------------------------------------------------------
BANG_CAN_DOI_KE_TOAN = [
    (None,  "TÀI SẢN", 0, "header"),
    ("100", "A - TÀI SẢN NGẮN HẠN", 0, "section"),
    ("110", "I. Tiền và các khoản tương đương tiền", 1, "total"),
    ("111", "1. Tiền", 2, "item"),
    ("112", "2. Các khoản tương đương tiền", 2, "item"),
    ("120", "II. Đầu tư tài chính ngắn hạn", 1, "total"),
    ("121", "1. Chứng khoán kinh doanh", 2, "item"),
    ("122", "2. Dự phòng giảm giá chứng khoán kinh doanh (*)", 2, "item"),
    ("123", "3. Đầu tư nắm giữ đến ngày đáo hạn", 2, "item"),
    ("130", "III. Các khoản phải thu ngắn hạn", 1, "total"),
    ("131", "1. Phải thu ngắn hạn của khách hàng", 2, "item"),
    ("132", "2. Trả trước cho người bán ngắn hạn", 2, "item"),
    ("133", "3. Phải thu nội bộ ngắn hạn", 2, "item"),
    ("134", "4. Phải thu theo tiến độ kế hoạch hợp đồng xây dựng", 2, "item"),
    ("135", "5. Phải thu về cho vay ngắn hạn", 2, "item"),
    ("136", "6. Phải thu ngắn hạn khác", 2, "item"),
    ("137", "7. Dự phòng phải thu ngắn hạn khó đòi (*)", 2, "item"),
    ("139", "8. Tài sản thiếu chờ xử lý", 2, "item"),
    ("140", "IV. Hàng tồn kho", 1, "total"),
    ("141", "1. Hàng tồn kho", 2, "item"),
    ("149", "2. Dự phòng giảm giá hàng tồn kho (*)", 2, "item"),
    ("150", "V. Tài sản ngắn hạn khác", 1, "total"),
    ("151", "1. Chi phí trả trước ngắn hạn", 2, "item"),
    ("152", "2. Thuế GTGT được khấu trừ", 2, "item"),
    ("153", "3. Thuế và các khoản khác phải thu Nhà nước", 2, "item"),
    ("154", "4. Giao dịch mua bán lại trái phiếu Chính phủ", 2, "item"),
    ("155", "5. Tài sản ngắn hạn khác", 2, "item"),
    ("200", "B - TÀI SẢN DÀI HẠN", 0, "section"),
    ("210", "I. Các khoản phải thu dài hạn", 1, "total"),
    ("211", "1. Phải thu dài hạn của khách hàng", 2, "item"),
    ("212", "2. Trả trước cho người bán dài hạn", 2, "item"),
    ("213", "3. Vốn kinh doanh ở đơn vị trực thuộc", 2, "item"),
    ("214", "4. Phải thu nội bộ dài hạn", 2, "item"),
    ("215", "5. Phải thu về cho vay dài hạn", 2, "item"),
    ("216", "6. Phải thu dài hạn khác", 2, "item"),
    ("219", "7. Dự phòng phải thu dài hạn khó đòi (*)", 2, "item"),
    ("220", "II. Tài sản cố định", 1, "total"),
    ("221", "1. Tài sản cố định hữu hình", 2, "item"),
    ("222", "- Nguyên giá", 3, "sub"),
    ("223", "- Giá trị hao mòn lũy kế (*)", 3, "sub"),
    ("224", "2. Tài sản cố định thuê tài chính", 2, "item"),
    ("225", "- Nguyên giá", 3, "sub"),
    ("226", "- Giá trị hao mòn lũy kế (*)", 3, "sub"),
    ("227", "3. Tài sản cố định vô hình", 2, "item"),
    ("228", "- Nguyên giá", 3, "sub"),
    ("229", "- Giá trị hao mòn lũy kế (*)", 3, "sub"),
    ("230", "III. Bất động sản đầu tư", 1, "total"),
    ("231", "- Nguyên giá", 3, "sub"),
    ("232", "- Giá trị hao mòn lũy kế (*)", 3, "sub"),
    ("240", "IV. Tài sản dở dang dài hạn", 1, "total"),
    ("241", "1. Chi phí sản xuất, kinh doanh dở dang dài hạn", 2, "item"),
    ("242", "2. Chi phí xây dựng cơ bản dở dang", 2, "item"),
    ("250", "V. Đầu tư tài chính dài hạn", 1, "total"),
    ("251", "1. Đầu tư vào công ty con", 2, "item"),
    ("252", "2. Đầu tư vào công ty liên doanh, liên kết", 2, "item"),
    ("253", "3. Đầu tư góp vốn vào đơn vị khác", 2, "item"),
    ("254", "4. Dự phòng đầu tư tài chính dài hạn (*)", 2, "item"),
    ("255", "5. Đầu tư nắm giữ đến ngày đáo hạn", 2, "item"),
    ("260", "VI. Tài sản dài hạn khác", 1, "total"),
    ("261", "1. Chi phí trả trước dài hạn", 2, "item"),
    ("262", "2. Tài sản thuế thu nhập hoãn lại", 2, "item"),
    ("263", "3. Thiết bị, vật tư, phụ tùng thay thế dài hạn", 2, "item"),
    ("268", "4. Tài sản dài hạn khác", 2, "item"),
    ("270", "TỔNG CỘNG TÀI SẢN", 0, "total"),
    (None,  "NGUỒN VỐN", 0, "header"),
    ("300", "C - NỢ PHẢI TRẢ", 0, "section"),
    ("310", "I. Nợ ngắn hạn", 1, "total"),
    ("311", "1. Phải trả người bán ngắn hạn", 2, "item"),
    ("312", "2. Người mua trả tiền trước ngắn hạn", 2, "item"),
    ("313", "3. Thuế và các khoản phải nộp Nhà nước", 2, "item"),
    ("314", "4. Phải trả người lao động", 2, "item"),
    ("315", "5. Chi phí phải trả ngắn hạn", 2, "item"),
    ("316", "6. Phải trả nội bộ ngắn hạn", 2, "item"),
    ("317", "7. Phải trả theo tiến độ kế hoạch hợp đồng xây dựng", 2, "item"),
    ("318", "8. Doanh thu chưa thực hiện ngắn hạn", 2, "item"),
    ("319", "9. Phải trả ngắn hạn khác", 2, "item"),
    ("320", "10. Vay và nợ thuê tài chính ngắn hạn", 2, "item"),
    ("321", "11. Dự phòng phải trả ngắn hạn", 2, "item"),
    ("322", "12. Quỹ khen thưởng, phúc lợi", 2, "item"),
    ("323", "13. Quỹ bình ổn giá", 2, "item"),
    ("324", "14. Giao dịch mua bán lại trái phiếu Chính phủ", 2, "item"),
    ("330", "II. Nợ dài hạn", 1, "total"),
    ("331", "1. Phải trả người bán dài hạn", 2, "item"),
    ("332", "2. Người mua trả tiền trước dài hạn", 2, "item"),
    ("333", "3. Chi phí phải trả dài hạn", 2, "item"),
    ("334", "4. Phải trả nội bộ về vốn kinh doanh", 2, "item"),
    ("335", "5. Phải trả nội bộ dài hạn", 2, "item"),
    ("336", "6. Doanh thu chưa thực hiện dài hạn", 2, "item"),
    ("337", "7. Phải trả dài hạn khác", 2, "item"),
    ("338", "8. Vay và nợ thuê tài chính dài hạn", 2, "item"),
    ("339", "9. Trái phiếu chuyển đổi", 2, "item"),
    ("340", "10. Cổ phiếu ưu đãi", 2, "item"),
    ("341", "11. Thuế thu nhập hoãn lại phải trả", 2, "item"),
    ("342", "12. Dự phòng phải trả dài hạn", 2, "item"),
    ("343", "13. Quỹ phát triển khoa học và công nghệ", 2, "item"),
    ("400", "D - VỐN CHỦ SỞ HỮU", 0, "section"),
    ("410", "I. Vốn chủ sở hữu", 1, "total"),
    ("411", "1. Vốn góp của chủ sở hữu", 2, "item"),
    ("411a", "- Cổ phiếu phổ thông có quyền biểu quyết", 3, "sub"),
    ("411b", "- Cổ phiếu ưu đãi", 3, "sub"),
    ("412", "2. Thặng dư vốn cổ phần", 2, "item"),
    ("413", "3. Quyền chọn chuyển đổi trái phiếu", 2, "item"),
    ("414", "4. Vốn khác của chủ sở hữu", 2, "item"),
    ("415", "5. Cổ phiếu quỹ (*)", 2, "item"),
    ("416", "6. Chênh lệch đánh giá lại tài sản", 2, "item"),
    ("417", "7. Chênh lệch tỷ giá hối đoái", 2, "item"),
    ("418", "8. Quỹ đầu tư phát triển", 2, "item"),
    ("419", "9. Quỹ hỗ trợ sắp xếp doanh nghiệp", 2, "item"),
    ("420", "10. Quỹ khác thuộc vốn chủ sở hữu", 2, "item"),
    ("421", "11. Lợi nhuận sau thuế chưa phân phối", 2, "item"),
    ("421a", "- LNST chưa phân phối lũy kế đến cuối kỳ trước", 3, "sub"),
    ("421b", "- LNST chưa phân phối kỳ này", 3, "sub"),
    ("422", "12. Nguồn vốn đầu tư XDCB", 2, "item"),
    ("429", "Lợi ích cổ đông không kiểm soát", 2, "item"),  # BCTC hợp nhất
    ("430", "II. Nguồn kinh phí và quỹ khác", 1, "total"),
    ("431", "1. Nguồn kinh phí", 2, "item"),
    ("432", "2. Nguồn kinh phí đã hình thành TSCĐ", 2, "item"),
    ("440", "TỔNG CỘNG NGUỒN VỐN", 0, "total"),
]

# ---------------------------------------------------------------------------
# B02-DN : BÁO CÁO KẾT QUẢ HOẠT ĐỘNG KINH DOANH
# ---------------------------------------------------------------------------
KET_QUA_KINH_DOANH = [
    ("01", "1. Doanh thu bán hàng và cung cấp dịch vụ", 0, "item"),
    ("02", "2. Các khoản giảm trừ doanh thu", 0, "item"),
    ("10", "3. Doanh thu thuần về bán hàng và cung cấp dịch vụ", 0, "total"),
    ("11", "4. Giá vốn hàng bán", 0, "item"),
    ("20", "5. Lợi nhuận gộp về bán hàng và cung cấp dịch vụ", 0, "total"),
    ("21", "6. Doanh thu hoạt động tài chính", 0, "item"),
    ("22", "7. Chi phí tài chính", 0, "item"),
    ("23", "- Trong đó: Chi phí lãi vay", 1, "sub"),
    ("24", "8. Phần lãi/lỗ trong công ty liên doanh, liên kết", 0, "item"),
    ("25", "9. Chi phí bán hàng", 0, "item"),
    ("26", "10. Chi phí quản lý doanh nghiệp", 0, "item"),
    ("30", "11. Lợi nhuận thuần từ hoạt động kinh doanh", 0, "total"),
    ("31", "12. Thu nhập khác", 0, "item"),
    ("32", "13. Chi phí khác", 0, "item"),
    ("40", "14. Lợi nhuận khác", 0, "total"),
    ("50", "15. Tổng lợi nhuận kế toán trước thuế", 0, "total"),
    ("51", "16. Chi phí thuế TNDN hiện hành", 0, "item"),
    ("52", "17. Chi phí thuế TNDN hoãn lại", 0, "item"),
    ("60", "18. Lợi nhuận sau thuế thu nhập doanh nghiệp", 0, "total"),
    ("61", "18.1. Lợi nhuận sau thuế của công ty mẹ", 1, "sub"),
    ("62", "18.2. Lợi nhuận sau thuế của cổ đông không kiểm soát", 1, "sub"),
    ("70", "19. Lãi cơ bản trên cổ phiếu (*)", 0, "item"),
    ("71", "20. Lãi suy giảm trên cổ phiếu (*)", 0, "item"),
]

# ---------------------------------------------------------------------------
# B03-DN : BÁO CÁO LƯU CHUYỂN TIỀN TỆ (phương pháp gián tiếp)
# ---------------------------------------------------------------------------
LUU_CHUYEN_TIEN_TE_GT = [
    (None, "I. Lưu chuyển tiền từ hoạt động kinh doanh", 0, "section"),
    ("01", "1. Lợi nhuận trước thuế", 1, "item"),
    (None, "2. Điều chỉnh cho các khoản:", 1, "header"),
    ("02", "- Khấu hao TSCĐ và BĐSĐT", 2, "sub"),
    ("03", "- Các khoản dự phòng", 2, "sub"),
    ("04", "- Lãi, lỗ chênh lệch tỷ giá hối đoái do đánh giá lại", 2, "sub"),
    ("05", "- Lãi, lỗ từ hoạt động đầu tư", 2, "sub"),
    ("06", "- Chi phí lãi vay", 2, "sub"),
    ("07", "- Các khoản điều chỉnh khác", 2, "sub"),
    ("08", "3. Lợi nhuận từ HĐKD trước thay đổi vốn lưu động", 1, "total"),
    ("09", "- Tăng, giảm các khoản phải thu", 2, "sub"),
    ("10", "- Tăng, giảm hàng tồn kho", 2, "sub"),
    ("11", "- Tăng, giảm các khoản phải trả (không kể lãi vay, thuế TNDN)", 2, "sub"),
    ("12", "- Tăng, giảm chi phí trả trước", 2, "sub"),
    ("13", "- Tăng, giảm chứng khoán kinh doanh", 2, "sub"),
    ("14", "- Tiền lãi vay đã trả", 2, "sub"),
    ("15", "- Thuế thu nhập doanh nghiệp đã nộp", 2, "sub"),
    ("16", "- Tiền thu khác từ hoạt động kinh doanh", 2, "sub"),
    ("17", "- Tiền chi khác cho hoạt động kinh doanh", 2, "sub"),
    ("20", "Lưu chuyển tiền thuần từ hoạt động kinh doanh", 1, "total"),
    (None, "II. Lưu chuyển tiền từ hoạt động đầu tư", 0, "section"),
    ("21", "1. Tiền chi mua sắm, XD TSCĐ và tài sản dài hạn khác", 1, "item"),
    ("22", "2. Tiền thu thanh lý, nhượng bán TSCĐ và tài sản dài hạn khác", 1, "item"),
    ("23", "3. Tiền chi cho vay, mua công cụ nợ của đơn vị khác", 1, "item"),
    ("24", "4. Tiền thu hồi cho vay, bán lại công cụ nợ của đơn vị khác", 1, "item"),
    ("25", "5. Tiền chi đầu tư góp vốn vào đơn vị khác", 1, "item"),
    ("26", "6. Tiền thu hồi đầu tư góp vốn vào đơn vị khác", 1, "item"),
    ("27", "7. Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia", 1, "item"),
    ("30", "Lưu chuyển tiền thuần từ hoạt động đầu tư", 1, "total"),
    (None, "III. Lưu chuyển tiền từ hoạt động tài chính", 0, "section"),
    ("31", "1. Tiền thu phát hành cổ phiếu, nhận vốn góp của CSH", 1, "item"),
    ("32", "2. Tiền trả lại vốn góp cho CSH, mua lại cổ phiếu đã phát hành", 1, "item"),
    ("33", "3. Tiền thu từ đi vay", 1, "item"),
    ("34", "4. Tiền trả nợ gốc vay", 1, "item"),
    ("35", "5. Tiền trả nợ gốc thuê tài chính", 1, "item"),
    ("36", "6. Cổ tức, lợi nhuận đã trả cho chủ sở hữu", 1, "item"),
    ("40", "Lưu chuyển tiền thuần từ hoạt động tài chính", 1, "total"),
    ("50", "Lưu chuyển tiền thuần trong kỳ", 0, "total"),
    ("60", "Tiền và tương đương tiền đầu kỳ", 0, "item"),
    ("61", "Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi ngoại tệ", 0, "item"),
    ("70", "Tiền và tương đương tiền cuối kỳ", 0, "total"),
]

# B03-DN phương pháp trực tiếp (một số DV/khách sạn dùng)
LUU_CHUYEN_TIEN_TE_TT = [
    (None, "I. Lưu chuyển tiền từ hoạt động kinh doanh", 0, "section"),
    ("01", "1. Tiền thu từ bán hàng, cung cấp dịch vụ và doanh thu khác", 1, "item"),
    ("02", "2. Tiền chi trả cho người cung cấp hàng hóa, dịch vụ", 1, "item"),
    ("03", "3. Tiền chi trả cho người lao động", 1, "item"),
    ("04", "4. Tiền lãi vay đã trả", 1, "item"),
    ("05", "5. Thuế thu nhập doanh nghiệp đã nộp", 1, "item"),
    ("06", "6. Tiền thu khác từ hoạt động kinh doanh", 1, "item"),
    ("07", "7. Tiền chi khác cho hoạt động kinh doanh", 1, "item"),
    ("20", "Lưu chuyển tiền thuần từ hoạt động kinh doanh", 1, "total"),
    (None, "II. Lưu chuyển tiền từ hoạt động đầu tư", 0, "section"),
    ("21", "1. Tiền chi mua sắm, XD TSCĐ và tài sản dài hạn khác", 1, "item"),
    ("22", "2. Tiền thu thanh lý, nhượng bán TSCĐ và tài sản dài hạn khác", 1, "item"),
    ("23", "3. Tiền chi cho vay, mua công cụ nợ của đơn vị khác", 1, "item"),
    ("24", "4. Tiền thu hồi cho vay, bán lại công cụ nợ của đơn vị khác", 1, "item"),
    ("25", "5. Tiền chi đầu tư góp vốn vào đơn vị khác", 1, "item"),
    ("26", "6. Tiền thu hồi đầu tư góp vốn vào đơn vị khác", 1, "item"),
    ("27", "7. Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia", 1, "item"),
    ("30", "Lưu chuyển tiền thuần từ hoạt động đầu tư", 1, "total"),
    (None, "III. Lưu chuyển tiền từ hoạt động tài chính", 0, "section"),
    ("31", "1. Tiền thu phát hành cổ phiếu, nhận vốn góp của CSH", 1, "item"),
    ("32", "2. Tiền trả lại vốn góp cho CSH, mua lại cổ phiếu đã phát hành", 1, "item"),
    ("33", "3. Tiền thu từ đi vay", 1, "item"),
    ("34", "4. Tiền trả nợ gốc vay", 1, "item"),
    ("35", "5. Tiền trả nợ gốc thuê tài chính", 1, "item"),
    ("36", "6. Cổ tức, lợi nhuận đã trả cho chủ sở hữu", 1, "item"),
    ("40", "Lưu chuyển tiền thuần từ hoạt động tài chính", 1, "total"),
    ("50", "Lưu chuyển tiền thuần trong kỳ", 0, "total"),
    ("60", "Tiền và tương đương tiền đầu kỳ", 0, "item"),
    ("61", "Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi ngoại tệ", 0, "item"),
    ("70", "Tiền và tương đương tiền cuối kỳ", 0, "total"),
]

# Tên sheet -> (template mặc định, tiêu đề đầy đủ)
STATEMENTS = {
    "CDKT":   ("Bảng cân đối kế toán", BANG_CAN_DOI_KE_TOAN),
    "KQHDKD": ("Báo cáo kết quả hoạt động kinh doanh", KET_QUA_KINH_DOANH),
    "LCTT":   ("Báo cáo lưu chuyển tiền tệ", LUU_CHUYEN_TIEN_TE_GT),
}


def codes_of(template):
    """Tập hợp mã số hợp lệ của một khung chỉ tiêu."""
    return {row[0] for row in template if row[0] is not None}
